### ISSUE TITLE
Wowza

### ISSUE THREAD

**Issue by MohMehrnia** [westonsoftware/vue-webrtc#133]
Hi, I used wowza and needed set application name and stream name,
 how do set when used you component

**Comment by westonsoftware** [comment]
Hi, it has been a while since I worked on Wowza but there is a player here that you can look at ...
https://github.com/koala-interactive/wowza-webrtc-player/

I seem to remember that they had custom sdp settings.

Our component lets you set these peerOptions but I think Wowza needs more than that ...
https://github.com/feross/simple-peer?tab=readme-ov-file#api
--Andy
